server:
  address: "server:12345"
loop:
  amount: 500
  period: "150ms"
log:
  level: "INFO"
batch:
  maxAmount: 10
apuesta:
  nombre: "Santiago Lionel"
  apellido: "Lorca"
  documento: "30904465"
  nacimiento: "1999-03-17"
  numero: "7574"