name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/agency-1.csv
        target: /agency.csv
    environment:
      - CLI_ID=1
      - CLI_NOMBRE=Santiago Lionel
      - CLI_APELLIDO=Lorca
      - CLI_DOCUMENTO=30904465
      - CLI_NACIMIENTO=1999-03-17
      - CLI_NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/agency-2.csv
        target: /agency.csv
    environment:
      - CLI_ID=2
      - CLI_NOMBRE=Santiago Lionel
      - CLI_APELLIDO=Lorca
      - CLI_DOCUMENTO=30904465
      - CLI_NACIMIENTO=1999-03-17
      - CLI_NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
