name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  netcat-test:
    container_name: netcat-test
    image: netcat-test:latest
    env_file: ./netcat-test/config.env
    networks:
      - testing_net
    depends_on:
      - server

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
